{
 "title": "Book database statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of authors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Количество авторов\"\nFROM authors;\n"
    }
   ]
  },
  {
   "title": "Number of books by publication date:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  publication_date::date AS \"time\",\n  COUNT(*) AS \"Количество книг\"\nFROM books\nGROUP BY publication_date\nORDER BY publication_date;\n"
    }
   ]
  },
  {
   "title": "Average book price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(price) AS \"Средняя цена\"\nFROM books;\n"
    }
   ]
  },
  {
   "title": "Number of books for each author:",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  a.name AS \"Автор\",\n  COUNT(ba.book_id) AS \"Количество книг\"\nFROM authors a\nJOIN book_authors ba ON a.author_id = ba.author_id\nGROUP BY a.name\nORDER BY COUNT(ba.book_id) DESC;\n"
    }
   ]
  },
  {
   "title": "Books with a quantity in stock less than 5",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  title AS \"Title\",\n  stock_quantity AS \"Quantity in stock\"\nFROM books\nWHERE stock_quantity < 5\nORDER BY stock_quantity;\n"
    }
   ]
  }
 ]
}