{
 "title": "Bookstore",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"java-application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collector jvm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"bookstore:8079\"} / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"bookstore:8079\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process memory usage MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"bookstore:8079\"} / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}