version: '3.8'

services:
  bookstore:
    image: glad2os/clh-bookstore
    container_name: clh-bookstore
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres/your_db_name
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db_name
    depends_on:
      postgres:
        condition: service_healthy

  auth:
    image: glad2os/clh-auth
    container_name: clh-auth
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_TOKEN=ahd8fee2ohboTh8eS9eeyoosaine3ohK
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=your_redis_password
      - REDIS_DB=0
    depends_on:
      - redis

  gateway:
    image: glad2os/clh-gateway
    container_name: clh-gateway
    environment:
      - AUTH_SERVICE_ADDRESS=clh-auth
      - BOOKSTORE_GRPC_HOST=clh-bookstore
      - BOOKSTORE_GRPC_PORT=8082
    ports:
      - "8081:8081"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_username -d your_db_name"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_redis_password
    volumes:
      - cache:/data

volumes:
  postgres_data:
    driver: local
  cache:
    driver: local
