apiVersion: 1

datasources:
- name: VictoriaMetrics
  type: prometheus
  access: proxy
  orgId: 1
  url: http://victoriametrics:8428
  isDefault: true
  version: 1
  editable: true

- name: PostgreSQL
  type: postgres
  access: proxy
  url: postgres:5432
  database: your_db_name
  user: your_username
  secureJsonData:
    password: your_password
  jsonData:
    sslMode: disable